server:
  port: 8082
spring:
  application:
    name: employee-service
eureka:
  instance:
    hostname: localhost
  cleint:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
managment:
  tracing:
    sampling:
      probability : 1.0