server:
  port: 8761
spring:
  application:
    name: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.insatnce.hostname}:${server.port}/eureka
managment:
  tracing:
    sampling:
      probability : 1.0